### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by YoonesImani** [RSATom/RtspRestreamServer#1]
I tried to compile your project on Ubuntu 17, but I got this error

RtspRestreamServer/RestreamServer/RtspMediaFactory.cpp:58:17: error: ‘GST_RTSP_TRANSPORT_MODE_PLAY_RECORD’ was not declared in this scope
         parent, GST_RTSP_TRANSPORT_MODE_PLAY_RECORD);

I think 'GST_RTSP_TRANSPORT_MODE_PLAY_RECORD' has not declared

**Comment by RSATom** [comment]
You have to use custom `gstreamer-rtsp-server`: https://github.com/RSATom/gst-rtsp-server

To simplify using, I've prepared PPA for it: https://launchpad.net/~rsatom/+archive/ubuntu/gst-rtsp-server-1.0

**Comment by RSATom** [comment]
I had to add build instructions, sorry. Will do it soon.

**Comment by RSATom** [comment]
I've added build instructions, but didn't test it on clean Ubuntu installation. So maybe missed something obvious...
